sudo: required
dist: trusty
language: cpp
cache:
  - apt
  - directories:
compiler:
  - g++
jdk: oraclejdk7
os:
  - unix
addons:
  ssh_known_hosts:
    - github.com

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - RABBITIM_USE_REPOSITORIES="TRUE"
    - QMAKE=qmake
    - RABBITIM_BUILD_THIRDLIBRARY="TRUE"
  matrix:
    - BUILD_TARGERT="unix" RABBIT_ARCH="unix" QT_VERSION_DIR=5.12 QT_VERSION=5.12.2
    - BUILD_TARGERT="unix" RABBIT_ARCH="unix" QT_VERSION_DIR=5.9 QT_VERSION=5.9.7
    - BUILD_TARGERT="unix" RABBIT_ARCH="unix" QT_VERSION_DIR=5.6 QT_VERSION=5.6.3
    #- BUILD_TARGERT="android" RABBIT_ARCH="armv7" QT_VERSION_DIR=5.12 QT_VERSION=5.12.2
    #- BUILD_TARGERT="android" RABBIT_ARCH="armv7" QT_VERSION_DIR=5.8 QT_VERSION=5.9.7
    #- BUILD_TARGERT="android" RABBIT_ARCH="armv7" QT_VERSION_DIR=5.6 QT_VERSION=5.6.3

before_install:
  - echo "TRAVIS_OS_NAME=${TRAVIS_OS_NAME}"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir ${SOURCE_DIR}/Tools

install:
  - cd ${SOURCE_DIR}
  - git clone https://github.com/KangLin/RabbitCommon.git
  - export RabbitCommon_DIR="`pwd`/RabbitCommon"
  - bash ci/build-install-tools.sh > /dev/null

before_script:
  - cd ${SOURCE_DIR}

script:
  - bash ${SOURCE_DIR}/ci/build.sh ${SOURCE_DIR}

#after_success:
  #- |
    #wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
    #chmod a+x linuxdeployqt-continuous-x86_64.AppImage
    #export VERSION="continuous"
    #./linuxdeployqt-continuous-x86_64.AppImage debian/serialportassistant/opt/SerialPortAssistant/share/applications/*.desktop -appimage

    #wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    #bash upload.sh Serial*.AppImage*

#branches:
#  except:
#    - # Do not build tags that we create when we upload to GitHub Releases
#    - /^(?i:continuous)$/

notifications:
  email: kl222@126.com
  on_success: never
  on_failure: always

#deploy:
#  - provider: releases
#    api_key:
#      secure: nYf7nWTSp5PnEow6DjKwiJJwhsdJTqFZd9KlvxFC7QOjsRyHtzpXM2SDK1BavOws/gK0GxtjYfpt2f4GTuQJvDB3mJsn4OKvVGlkKtBFhTNDMVZjehhbgvmeivvtQ+NI8gbQtkI29oXes0ToKqvUV94WL5wRJwcUnfFvinJmxIHhlfQ3/nf9C1KAgFQ2oAiWCj+pOj54LEdEfBnqZfbpBvalwW4PWPB4lBLFvQpyNJhdcxHrl8Cvo8qfq07glPNoD4HLFaGhAQ+hxCcoC5cgrQxsGu9sVyHgHXj0a3BV520Aa946WrR4P0yHQnECH169WY4ZzPcpZjJyd0l+gC37sggAjQsXw+LwLOB/uFY7Ipg8xquHIYPDC8UUdfPBVcd0aJ+u7Mb7CUUnwCZ1gL/w1oi1TFyEJcCp/HznparCQAdiyaX6BBXghxKAYRWMBDGvFAx5gZv2OaocRIOdGLAIXGL43vLKbuLjNj2syLB2GzG5uPaOgaZQyYlIhd/iU6r55Ih2XMCGsTOwCOSy+Y1+ULGBoP7ZE8AuVlHxn9MZQoZg24IVqlXgIr/bEtcSwIi0wCKfjvsD3TjMSwAr6stilhHmJ6ldB9B+TAX6TdxB/NUDDxaxG2ZoYXOWOanBv02FYc/Opbq8WA3vv6AlE+FAqOtdcc8ULBC4rz8Q8UOro6U=
#    file: serialportassistant_*_amd64.deb

#    skip_cleanup: true
    #draft: true
#    on:
#      tags: true
#      condition: "$BUILD_TARGERT=unix && $QT_VERSION=5.12.2"
