#TODO: Change version
version: 'v0.2.0-5-g66405df.{build}'

environment:
  matrix: 
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.9.1
    QT_ROOT: /C/Qt/5.9.1/msvc2015
    AUTOBUILD_ARCH: x86

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.9.1
    QT_ROOT: /C/Qt/5.9.1/msvc2015_64
    AUTOBUILD_ARCH: x64
   
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.9.1
    QT_ROOT: /C/Qt/5.9.1/msvc2013_64
    AUTOBUILD_ARCH: x64
    
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.8.0
    QT_ROOT: /C/Qt/5.8/msvc2015
    AUTOBUILD_ARCH: x86

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.8.0
    QT_ROOT: /C/Qt/5.8/msvc2015_64
    AUTOBUILD_ARCH: x64

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.7.1
    QT_ROOT: /C/Qt/5.7/msvc2015
    AUTOBUILD_ARCH: x86

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.7.1
    QT_ROOT: /C/Qt/5.7/msvc2015_64
    AUTOBUILD_ARCH: x64

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.6.2
    QT_ROOT: /C/Qt/5.6/msvc2015
    AUTOBUILD_ARCH: x86

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    QT_VERSION: qt5.6.2
    QT_ROOT: /C/Qt/5.6/msvc2015_64
    AUTOBUILD_ARCH: x64

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.7.1
    QT_ROOT: /C/Qt/5.7/msvc2013
    AUTOBUILD_ARCH: x86 

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.7.1
    QT_ROOT: /C/Qt/5.7/msvc2013_64
    AUTOBUILD_ARCH: x64 

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    TOOLCHAIN_VERSION: 12
    QT_VERSION: qt5.6.2
    QT_ROOT: /C/Qt/5.6/msvc2013
    AUTOBUILD_ARCH: x86

  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530
    QT_VERSION: qt5.9.0
    QT_ROOT: /C/Qt/5.9/mingw53_32
    AUTOBUILD_ARCH: x86
    
  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530
    QT_VERSION: qt5.8.0
    QT_ROOT: /C/Qt/5.8/mingw53_32
    AUTOBUILD_ARCH: x86
  
  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 530
    QT_VERSION: qt5.7.1
    QT_ROOT: /C/Qt/5.7/mingw53_32
    AUTOBUILD_ARCH: x86
      
  - BUILD_TARGERT: windows_mingw
    TOOLCHAIN_VERSION: 492
    QT_VERSION: qt5.6.2
    QT_ROOT: /C/Qt/5.6/mingw49_32
    AUTOBUILD_ARCH: x86

matrix:
  fast_finish: false

init:
  - set BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
  - set varch=%AUTOBUILD_ARCH%
  - if "%AUTOBUILD_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGERT%"=="windows_msvc" call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%
  #- if "%BUILD_TARGERT%"=="windows_mingw" set PATH=C:\Qt\Tools\mingw%TOOLCHAIN_VERSION%_32\bin;%PATH%
  - if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - echo QT_ROOT=%QT_ROOT%
  - del C:\msys64\usr\bin\link.exe

install:
  - C:\msys64\autorebase.bat

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - if "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build-install-tools-windows.sh

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build.sh

artifacts:
  - path: build_${BUILD_TARGERT}/SerialPortAssistant-Setup-*.exe
    #name: SerialPortAssistant_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    type: zip

test: off

deploy:
  - provider: GitHub
    #release: SerialPortAssistant_-v$(appveyor_build_version)
    description: 'Release SerialPortAssistant_$(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: xgIFN2iAfgj1gsWabdHrmFXvj0rce/ZWtKUwm3aDUNfLGu+kO/q94MYD8a46AbDL
    #artifact: SerialPortAssistant_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(AUTOBUILD_ARCH)_$(QT_VERSION)_v$(appveyor_build_version)
    #draft: true
    #prerelease: true
    on:
      BUILD_TARGERT: windows_msvc
      TOOLCHAIN_VERSION: 14
      QT_VERSION: qt5.7.1
      AUTOBUILD_ARCH: x86
      appveyor_repo_tag: true        # deploy on tag push only
